import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/shared";

const openSans = Open_Sans({
	weight: "500",
	subsets: ['cyrillic']
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
				<Header />
				<main className='min-h-screen'>
        	{children}
				</main>
      </body>
    </html>
  );
}
