import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/shared";

const openSans = Open_Sans({
	weight: ["500", "800"],
	subsets: ['cyrillic'],
	style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
				<Header />
				<main className='min-h-screen'>
        	{children}
				</main>
      </body>
    </html>
  );
}
