import { Container, Footer, Header } from '@/shared/components/shared'

export const metadata = {
  title: 'Next Vinauto | Корзина',
  description: 'Generated by create next app',
}

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Header
        hasSearch={false}
        hasCart={false}
      />
      <Container>{children}</Container>
      <Footer />
    </main>
  )
}
